name: Deploy domains
on:
  push:
    branches:
      - main
    paths:
      - 'domains/**/*'
permissions:
  id-token: write
  contents: read
jobs:
  leebriggs_co_uk:
    name: Update
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: npm install
        working-directory: domains/leebriggs.co.uk
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: githubactions
          aws-region: us-west-2
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: production
          work-dir: domains/leebriggs.co.uk
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  lbrlabs_com:
    name: Update
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: npm install
        working-directory: domains/lbrlabs.com
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: githubactions
          aws-region: us-west-2
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: production
          work-dir: domains/lbrlabs.com
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}