name: Deploy network
on:
  push:
    branches:
      - main
    paths:
      - 'network/**/*'
permissions:
  id-token: write
  contents: read
defaults:
  run:
    shell: bash
    working-directory: network
jobs:
  network:
    name: Update
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: npm install
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: githubactions
          aws-region: us-west-2
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: production
          work-dir: network
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}